### ISSUE TITLE
Implement Synergy Wholesale

### ISSUE THREAD

**Issue by sdelemos** [upmind-automation/provision-provider-domain-names#16]
Synergy Wholesale is a big provider here in Australia, some of the best rates on .com.au as well as a large offering of TLD's - They bill in AU and are generally a go to provider here.

Docs are below, would be good to see them considered. 

https://synergywholesale.com/wp-content/uploads/2022/11/Synergy-Wholesale-API-Documentation-v3-8.pdf

https://upmind.com/community/topic/615-synergy-wholesale-domain-provider/

**Comment by xyzulu** [comment]
Synergy already has some their modules on GitHub.  This should be an easy integration to support. 

See https://github.com/SynergyWholesale/WHMCS-Domains-Module/releases/latest

**Comment by xyzulu** [comment]
It looks like this has now been implemented, correct?

**Comment by sdelemos** [comment]
Correct - Synergy Wholesale is live on Upmind

**Comment by xyzulu** [comment]
I've reported a bug (can't register .au domains) via your ticket system.. or would you prefer it here?
