### ISSUE TITLE
ConnectReseller CompanyName

### ISSUE THREAD

**Issue by sdelemos** [upmind-automation/provision-provider-domain-names#25]
From what I can determine, it seems the ConnectReseller API no longer accepts empty Company Name (Organisation). We will push a fix out so that when no Organisation is entered, we use the Name as CompanyName in the ConnectReseller API call.

**Comment by uphlewis** [comment]
Fixed in https://github.com/upmind-automation/provision-provider-domain-names/releases/tag/v2.0.2
