### ISSUE TITLE
RealtimeRegister configuration validation error

### ISSUE THREAD

**Issue by elviravinky** [upmind-automation/provision-provider-domain-names#64]
When you set up the integration the "customer" field required values at least 6 characters long, but when I signed up for Realtime Register they issued me a customer name that is 5 characters long. I therefore cannot set up the integrations and everything is stalled until this is fixed. Here are 2 screenshots, the first is upmind and the second is the realtime register customer portal.[https://upmind.com/community/topic/837-urgent-the-customer-must-be-at-least-6-characters-realtime-register/](url)

**Comment by uphlewis** [comment]
Thanks for reporting this issue, will get this fixed!

**Comment by uphlewis** [comment]
https://github.com/upmind-automation/provision-provider-domain-names/releases/tag/v2.8.6
